language: php
php:
  - 5.4
install:
  - composer install
script:
  - php vendor/bin/phpcs --standard=PSR2 app/Judge
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
